title: "Giovana Morais"
author: "Giovana Morais"
email: giovana.vmorais@gmail.com

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)

theme_config:
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

highlighter: rouge

navigation:
 - name: About
   link: /about
 # - name: Projects
 #   link: /projects
 # - name: CV
 #   link: /resume
 - name: Research
   link: /publications
 - name: Blog
   link: /blog
